AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SBC-RT

  SAM Template for SBC-RT

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: SBC-RT/
      Handler: app.lambda_handler
      Layers:
        - arn:aws:lambda:ca-central-1:131565110619:layer:psycopg2:1     # Layer for python3.8 compatible psycopg2 library
        - arn:aws:lambda:ca-central-1:131565110619:layer:matplotlib:2 $ # Layer for python3.8 compatible matplotlib library
        - arn:aws:lambda:ca-central-1:778625758767:layer:AWSLambda-Python38-SciPy1x:29 # AWS Layer for scipy/numpy
      Runtime: python3.8

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LambdaFunction:
    Description: "SBC RT Lambda Function ARN"
    Value: !GetAtt LambdaFunction.Arn
  LambdaFunctionIamRole:
    Description: "Implicit IAM Role created for SBC RT function"
    Value: !GetAtt LambdaFunctionRole.Arn
